"""Tour inventory for Belize Shore Excursion (editorial route catalogue for Phase 13B)."""

TOURS: list[dict] = [
    {
        "slug": "cave-tubing-and-zip-line-combo",
        "title": "Cave Tubing and Zip Line Combo",
        "seg_desc": "Explore the rainforest by air, land, and water with cave tubing, nature walking, and zip lining.",
        "duration": "6 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "combo",
        "badge": "Best Adventure Combo",
        "featured": True,
    },
    {
        "slug": "belize-cave-tubing",
        "title": "Belize Cave Tubing",
        "seg_desc": "Tubing through Belize's unique underground cave system on a shared shore excursion from the cruise tender pier.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "cave",
        "badge": "Best Cave Tubing",
        "featured": True,
    },
    {
        "slug": "turtle-snorkel-and-island-time",
        "title": "Turtle Snorkel and Island Time",
        "seg_desc": "Snorkel at two sites with time at Caye Caulker — wildlife sightings are never guaranteed.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "snorkel",
        "badge": "Best Reef Snorkel",
        "featured": True,
    },
    {
        "slug": "altun-ha-and-belize-city-overview",
        "title": "Altun-Ha and Belize City Overview",
        "seg_desc": "Visit Mayan ruins dating back to 200 BC and enjoy an overview of Belize City.",
        "duration": "4 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "ruins",
        "badge": "Best Ruins & City",
        "featured": True,
    },
    {
        "slug": "belize-city-and-zoo-combo",
        "title": "Belize City and Zoo Combo",
        "seg_desc": "Walk on the wild side at the Belize Zoo and see top Belize City attractions including St. John's Cathedral.",
        "duration": "5 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "zoo",
        "badge": "Best Family Combo",
        "featured": False,
    },
    {
        "slug": "altun-ha-and-jeep-adventure",
        "title": "Altun-Ha and Jeep Adventure",
        "seg_desc": "Climb temples at Altun-Ha, explore a cave system and enjoy a thrilling Jeep ride through the Belizean countryside.",
        "duration": "6 Hours",
        "activity": "Moderate",
        "size": "Small",
        "category": "jeep",
        "badge": "Best Small-Group Adventure",
        "featured": False,
    },
    {
        "slug": "shark-ray-alley-and-caye-caulker-beach-break",
        "title": "Shark Ray Alley and Caye Caulker Beach Break by Boat",
        "seg_desc": "Swim with nurse sharks and sting rays at Shark Ray Alley, then relax with a beach break at Caye Caulker Island.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "beach",
        "badge": "Best Beach & Snorkel",
        "featured": True,
    },
    {
        "slug": "altun-ha-and-river-wallace",
        "title": "Altun Ha and River Wallace",
        "seg_desc": "Explore Mayan ruins of Altun Ha and glimpse local wildlife on a cultural tour of River Wallace and Altun Ha.",
        "duration": "5 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "ruins",
        "badge": "Best Easy Ruins Tour",
        "featured": False,
    },
    {
        "slug": "jungle-jeep-adventure-and-beach-break",
        "title": "Jungle Jeep Adventure and Beach Break",
        "seg_desc": "Jeep through Belizean rainforest with a hidden cave system, then lunch and beach time in Old Belize.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "jeep",
        "badge": "Best Jeep & Beach",
        "featured": False,
    },
    {
        "slug": "altun-ha-mayan-ruins-and-tropical-jungle-monkey-reserve",
        "title": "Altun Ha Mayan Ruins and Tropical Jungle Monkey Reserve",
        "seg_desc": "Tour Altun Ha where Mayans burned offerings to the gods, then visit the Belize Community Baboon Sanctuary.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Standard",
        "category": "wildlife",
        "badge": "Best Ruins & Wildlife",
        "featured": False,
    },
    {
        "slug": "river-wallace-and-burrell-boom",
        "title": "River Wallace and Burrell Boom",
        "seg_desc": "Cruise the coast of Belize City and along the Belize River with a stop at a historic village.",
        "duration": "5 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "city",
        "badge": "Best River Cruise",
        "featured": False,
    },
    {
        "slug": "jungle-jeep-adventure-and-sibun-wildlife-river-cruise",
        "title": "Jungle Jeep Adventure And Sibun Wildlife River Cruise",
        "seg_desc": "Jeep over bumpy roads through a dry cave system, then a crocodile-studded river cruise on the Sibun River.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Standard",
        "category": "jeep",
        "badge": "Best Jeep & River",
        "featured": False,
    },
    {
        "slug": "jungle-zip-line",
        "title": "Jungle Zip Line",
        "seg_desc": "Experience the jungle of Belize on a thrilling zipline adventure through the rainforest canopy.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "zip",
        "badge": "Best Zip Line",
        "featured": False,
    },
    {
        "slug": "jungle-jeep-adventure",
        "title": "Jungle Jeep Adventure",
        "seg_desc": "An UN-BELIZEABLE Jeep experience to hidden parts of nature's best kept secrets in Belize.",
        "duration": "4 Hours",
        "activity": "Moderate",
        "size": "Small",
        "category": "jeep",
        "badge": "Best Small-Group Jeep",
        "featured": False,
    },
    {
        "slug": "belize-jungle-jeep-rum-factory-and-museum-tour",
        "title": "Belize Jungle Jeep, Rum Factory and Museum Tour",
        "seg_desc": "Jeep through rainforest, explore a cave system, tour a rum factory and museum in Belize City.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "jeep",
        "badge": "Best Culture & Jeep",
        "featured": False,
    },
    {
        "slug": "baboon-sanctuary-and-jeep-adventure",
        "title": "Baboon Sanctuary and Jeep Adventure",
        "seg_desc": "Watch Black Howler Monkeys at the Community Baboon Sanctuary then a Jeep ride through the countryside.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Small",
        "category": "wildlife",
        "badge": "Best Wildlife Jeep",
        "featured": False,
    },
    {
        "slug": "zip-line-and-belize-zoo-with-lunch",
        "title": "Zip Line and Belize Zoo with Lunch",
        "seg_desc": "Zipline across lush canopies, visit the Belize Zoo, and enjoy Belizean cuisine on this eco-tour.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Standard",
        "category": "combo",
        "badge": "Best Zip & Zoo",
        "featured": False,
    },
    {
        "slug": "belize-zoo-and-jeep-adventure",
        "title": "Belize Zoo and Jeep Adventure",
        "seg_desc": "See Chiqui the Jaguar cub, Fuego the Tapir and more at the Belize Zoo, then a Jeep countryside ride.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Small",
        "category": "zoo",
        "badge": "Best Zoo Adventure",
        "featured": False,
    },
    {
        "slug": "journey-to-cahal-pech",
        "title": "Journey to Cahal Pech",
        "seg_desc": "Tour the ruins of Cahal Pech with a historical tour of Belize City along the way.",
        "duration": "6 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "ruins",
        "badge": "Best Cahal Pech Tour",
        "featured": False,
    },
    {
        "slug": "adventure-to-altun-ha-and-belize-zoo",
        "title": "Adventure to Altun Ha and Belize Zoo",
        "seg_desc": "Journey to ancient Altun Ha with the Temple of the Sun God and Temple of the Masonry Altars in the rainforest.",
        "duration": "5 Hours 30 Minutes",
        "activity": "Easy",
        "size": "Standard",
        "category": "ruins",
        "badge": "Best Ruins & Zoo",
        "featured": False,
    },
    {
        "slug": "howler-monkey-sanctuary",
        "title": "Howler Monkey Sanctuary",
        "seg_desc": "Experience Black Howler monkeys up close on this fun, family-friendly rainforest excursion.",
        "duration": "3 Hours 30 Minutes",
        "activity": "Easy",
        "size": "Standard",
        "category": "wildlife",
        "badge": "Best Short Wildlife",
        "featured": False,
    },
    {
        "slug": "lamanai-eco-adventure",
        "title": "Lamanai Eco Adventure",
        "seg_desc": "One of the largest and most interesting Mayan sites in Belize — river boat access through jungle waterways.",
        "duration": "6 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "lamanai",
        "badge": "Best Lamanai Tour",
        "featured": True,
    },
    {
        "slug": "belize-city-and-rum-factory-tour",
        "title": "Belize City and Rum Factory Tour",
        "seg_desc": "A short Belize rum factory and city tour — long on taste, perfect for shorter port windows.",
        "duration": "2 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "city",
        "badge": "Best Short City Tour",
        "featured": False,
    },
    {
        "slug": "city-sightseeing-and-highlights",
        "title": "City Sightseeing and Highlights",
        "seg_desc": "Colonial capital views, beach time, Memorial Park and Baron Bliss Lighthouse on a cultural city tour.",
        "duration": "2 Hours",
        "activity": "Easy",
        "size": "Small",
        "category": "city",
        "badge": "Best City Highlights",
        "featured": False,
    },
    {
        "slug": "cave-tubing-and-jungle-trek-with-lunch",
        "title": "Cave Tubing and Jungle Trek with Lunch",
        "seg_desc": "Float through limestone caves that once served as Mayan ceremonial grounds with a jungle trek and lunch.",
        "duration": "5 Hours",
        "activity": "Moderate",
        "size": "Small",
        "category": "cave",
        "badge": "Best Small-Group Cave",
        "featured": False,
    },
    {
        "slug": "beach-and-city",
        "title": "Beach and City",
        "seg_desc": "Snorkel on Belize's barrier reef, sunbathe at Goff's Caye, and visit historical Belize City landmarks.",
        "duration": "5 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "beach",
        "badge": "Best Reef & City",
        "featured": False,
    },
    {
        "slug": "barrier-reef-snorkel",
        "title": "Barrier Reef Snorkel",
        "seg_desc": "Explore Caye Caulker and the Belize Barrier Reef on an underwater adventure and island getaway.",
        "duration": "5 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "snorkel",
        "badge": "Best Barrier Reef",
        "featured": False,
    },
    {
        "slug": "kukumba-beach-and-city",
        "title": "Kukumba Beach and City",
        "seg_desc": "Relax at Kukumba Beach and experience the Old Belize train ride on this Belize City tour.",
        "duration": "5 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "beach",
        "badge": "Best City Beach",
        "featured": False,
    },
    {
        "slug": "xunantunich-and-cave-tubing",
        "title": "Xunantunich and Cave Tubing",
        "seg_desc": "Explore Xunantunich ruins and journey down a river through underground caves on this cultural tour.",
        "duration": "6 Hours 30 Minutes",
        "activity": "Moderate",
        "size": "Small",
        "category": "combo",
        "badge": "Best Ruins & Cave",
        "featured": False,
    },
    {
        "slug": "belize-party-bus",
        "title": "Belize Party Bus",
        "seg_desc": "A Caribbean party bus experience sight-seeing around Belize City with music and continuous energy.",
        "duration": "2 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "city",
        "badge": "Best Fun City Tour",
        "featured": False,
    },
    {
        "slug": "adventure-to-altun-ha",
        "title": "Adventure to Altun Ha",
        "seg_desc": "Stroll through two main plazas and the Temple of the Sun God at Altun Ha — witness the famous Jade Head.",
        "duration": "3 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "ruins",
        "badge": "Best Compact Ruins",
        "featured": False,
    },
    {
        "slug": "altun-ha-mayan-ruins-and-wildlife-of-the-belize-zoo",
        "title": "Altun Ha Mayan Ruins and Wildlife of the Belize Zoo",
        "seg_desc": "Explore magnificent Altun Ha and the majestic Belize Zoo on one history-and-nature shore day.",
        "duration": "6 Hours",
        "activity": "Moderate",
        "size": "Standard",
        "category": "ruins",
        "badge": "Best Full-Day Ruins",
        "featured": False,
    },
    {
        "slug": "expedition-to-crooked-tree-wildlife-sanctuary",
        "title": "Expedition to Crooked Tree Wildlife Sanctuary",
        "seg_desc": "Discover the vibrant Crooked Tree Wildlife Sanctuary — crafted for nature lovers and birdwatchers.",
        "duration": "5 Hours",
        "activity": "Easy",
        "size": "Standard",
        "category": "wildlife",
        "badge": "Best Birdwatching",
        "featured": False,
    },
    {
        "slug": "private-tubing-expedition",
        "title": "Private Tubing Expedition",
        "seg_desc": "Private tubing through interconnected cave systems with stalactites, stalagmites and captivating formations.",
        "duration": "5 Hours",
        "activity": "Difficult",
        "size": "Private",
        "category": "private",
        "badge": "Best Private Adventure",
        "featured": True,
    },
]

TOUR_PAGES = [t["slug"] for t in TOURS]
FEATURED_TOURS = [t["slug"] for t in TOURS if t.get("featured")]

SITEMAP_PAGES = [
    ("", "1.0", "weekly"),
    ("best-belize-shore-excursions.html", "0.9", "monthly"),
    ("belize-cruise-port-guide.html", "0.8", "monthly"),
    ("one-day-in-belize-from-a-cruise-ship.html", "0.8", "monthly"),
    ("belize-private-tours.html", "0.8", "monthly"),
    ("belize-snorkeling-and-beach-excursions.html", "0.8", "monthly"),
    ("belize-mayan-ruins-excursions.html", "0.8", "monthly"),
    ("belize-shore-excursions-faq.html", "0.8", "monthly"),
] + [(f"{slug}.html", "0.9", "monthly") for slug in TOUR_PAGES]
